site_name: blex.bio
site_description: Scientist–programmer building bioinformatics infrastructure.
site_url: https://blex.bio
repo_url: https://github.com/blex-max
repo_name: GitHub
copyright: "© Alex Byrne"

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.action.edit
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/blex-max
    - icon: material/email
      link: mailto:alex@blex.bio

plugins:
  - search
  - minify

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.emoji

nav:
  - Home: index.md
  - Projects: projects.md
  - Notes:
      - Overview: notes/_index.md
      - First post: notes/init-post.md
